/*
 * Copyright 2013-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.data.analysis.demos.web;

import com.example.data.analysis.entity.User;
import com.example.data.analysis.service.UserService;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import lombok.AllArgsConstructor;
import org.springframework.web.bind.annotation.*;

/**
 * @author <a href="mailto:chenxilzx1@gmail.com">theonefx</a>
 */
@RestController
@AllArgsConstructor
@RequestMapping("/ceshi")
@Api(description  = "测试模块")
public class BasicController {

    private final UserService userService;

    // http://127.0.0.1:8080/hello?name=lisi
    @GetMapping("/hello")
    @ResponseBody
    @ApiOperation(value = "测试hello",httpMethod = "GET",response = User.class)
    public String hello(@RequestParam(name = "name", defaultValue = "unknown user") String name) {
        userService.list();
        return "Hello " + name;
    }

    // http://127.0.0.1:8080/user
    @PostMapping("/user")
    @ResponseBody
    public User user() {
        User user = new User();
        user.setName("theonefx");
        return user;
    }

    // http://127.0.0.1:8080/save_user?name=newName&age=11
    @RequestMapping("/save_user")
    @ResponseBody
    public String saveUser(User u) {
        return "user will save: name=" + u.getName() ;
    }

    // http://127.0.0.1:8080/html
    @RequestMapping("/html")
    public String html() {
        return "/html/login.html";
    }

    @ModelAttribute
    public void parseUser(@RequestParam(name = "name", defaultValue = "unknown user") String name
            , @RequestParam(name = "age", defaultValue = "12") Integer age, User user) {
        user.setName("zhangsan");

    }

    /**
     * Example Code generated by Beijing Volcanoengine Technology.
     */

}
